Project.MVCAdmin/Controllers/SaloonController.cs
using Project.BLL.Repositories.ConcRep;
using Project.ENTITIES.Models;
using Project.MVCAdmin.Models.CustomTools;
using Project.MVCAdmin.Models.PageVMs;
using Project.VM.PureVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Project.MVCAdmin.Controllers
{
    public class SaloonController : Controller
    {
        SaloonRepository _saloonRep;
        public SaloonController()
        {
            _saloonRep = new SaloonRepository();

        }
        public ActionResult Index()
        {
            List<SaloonVM> saloons = _saloonRep.
                Where(x => x.Status != ENTITIES.Enums.DataStatus.Deleted).Select(x => new SaloonVM
                {
                    ID = x.ID,
                    Capacity = x.Capacity,
                    SaloonNumber = x.SaloonNumber,

                }).ToList();

            ListSaloonPageVM lspvm = new ListSaloonPageVM
            {
                Saloons = saloons,
            };

            return View(lspvm);

        }

        [HttpGet]
        public ActionResult AddSaloon()
        {
            return View();
        }



        [HttpPost]
        public ActionResult AddSaloon(SaloonVM saloon)
        {
            Saloon s = new Saloon
            {
                ID = saloon.ID,
                SaloonNumber = saloon.SaloonNumber,
                Capacity = saloon.Capacity,


            };
            _saloonRep.Add(s);
            return View();
        }
        [HttpGet]
        public ActionResult UpdateSaloon(int id)
        {
            AddUpdateSaloonPageVM updatesaloonpagevm = new AddUpdateSaloonPageVM
            {
                Saloon = _saloonRep.Where(x => x.ID == id).Select(x => new SaloonVM
                {
                    ID = x.ID,
                    SaloonNumber = x.SaloonNumber,
                    Capacity = x.Capacity,

                }).FirstOrDefault()
            };
            return View(updatesaloonpagevm);
        }

        [HttpPost]
        public ActionResult UpdateSaloon(SaloonVM saloon)
        {
            Saloon updated = _saloonRep.Find(saloon.ID);
            updated.Capacity = saloon.Capacity;
            updated.SaloonNumber = saloon.SaloonNumber;


            _saloonRep.Update(updated);
            return RedirectToAction("Index");

        }
        public ActionResult DeleteSaloon(int id)
        {
            _saloonRep.Delete(_saloonRep.Find(id));

            return RedirectToAction("Index");

        }
    }
}

Project.MVCAdmin/Views/Saloon/AddSaloon.cshtml
@model AddUpdateSaloonPageVM
@{
    ViewBag.Title = "AddSaloon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="page-header">
    <h2>Salon Ekle</h2>

    <div class="right-wrapper text-end">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="bx bx-home-alt"></i>
                </a>
            </li>

            <li><span>Salonlar</span></li>

            <li><span>Salon Ekle</span></li>

        </ol>

    </div>
</header>

<!-- start: page -->
<div class="row">
    <div class="col">
        <section class="card">
            <header class="card-header">
                <div class="card-actions">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
                </div>

                <h2 class="card-title">Salon Ekle</h2>
            </header>
            <div class="card-body">
                @using (Html.BeginForm("AddSaloon", "Saloon", FormMethod.Post, new { role = "form" }))
                {
                
                <form class="form-horizontal form-bordered" method="post" action="/Saloon/AddSaloon">
                    <div class="form-group row pb-4">
                        <label class="col-lg-3 control-label text-lg-end pt-2"
                               for="inputDefault">Salon Number</label>
                        <div class="col-lg-6">
                            @*<input type="text" class="form-control" id="SaloonNumber">*@
                            @Html.TextBoxFor(x => x.Saloon.SaloonNumber, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group row pb-4">
                        <label class="col-lg-3 control-label text-lg-end pt-2"
                               for="inputDefault">Salon Kapasitesi</label>
                        <div class="col-lg-6">
                            @*<input type="text" class="form-control" id="Capacity">*@
                            @Html.TextBoxFor(x => x.Saloon.Capacity, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2">İşlem:</label>
                        <div class="col-sm-10">
                            <button class="btn btn-gradient">Ekle</button>
                        </div>
                    </div>
                </form>
                }
            </div>
        </section>
    </div>
</div>
<!-- end: page -->

Project.MVCAdmin/Views/Saloon/Index.cshtml
@model ListSaloonPageVM
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<header class="page-header">
    <h2>Salon Listesi</h2>

    <div class="right-wrapper text-end">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="bx bx-home-alt"></i>
                </a>
            </li>

            <li><span>Salon Yönetimi</span></li>

            <li><span>Salon Listesi</span></li>

        </ol>

    </div>
</header>

<!-- start: page -->
<section class="card">
    <header class="card-header">

        <h2 class="card-title">Salon Listesi</h2>
    </header>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-3">
                    <a id="addToTable" href="/Saloon/AddSaloon" class="btn btn-gradient">Yeni Ekle <i class="fas fa-plus"></i></a>
                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped mb-0" id="datatable-editable">
            <thead>
                <tr>
                    <th>Salon Numarası</th>
                    <th>Kapasite</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var saloonVM in Model.Saloons)
                {
                    <tr data-item-id="1">
                        <td>
                            @saloonVM.SaloonNumber
                        </td>
                        <td>
                            @saloonVM.Capacity
                        </td>
                        <td class="actions">
                            <a
                               href="/Saloon/UpdateSaloon/@saloonVM.ID" class="on-default edit-row">
                              
                            <i class="fas fa-pencil-alt"></i></a>
                            <a href="/Saloon/DeleteSaloon/@saloonVM.ID" class="on-default remove-row"
                                onclick="return confirm('Bu Salonu sildiğinizde bağlı olan tüm seansları da silinecketir! Bu salonu silmek istediğinize emini misiniz ? ')">
                            <i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>
<!-- end: page -->

Project.MVCAdmin/Views/Saloon/ListSaloons.cshtml
@model ListSaloonPageVM
@{
    ViewBag.Title = "ListSaloons";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="panel-heading">
    @Html.ActionLink("Salon Ekle", "AddSaloon", null, new { @class = "btn btn-primary" })
</header>

<div class="panel-body">
    <div class="adv-table">
        <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
            <thead>
                <tr>
                    <th>Saloon ID</th>
                    <th class="hidden-phone">Saloon Number</th>
                    <th class="hidden-phone">Saloon Kapasite</th>
                    

                    <th class="hidden-phone">Sil</th>
                    <th class="hidden-phone">Güncelle</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model.Saloons)
                {
                    <tr class="gradeX">




                        <td>@item.ID</td>
                        <td>@item.Capacity</td>
                        <td class="hidden-phone">@item.SaloonNumber</td>
                        
                        <td class="center hidden-phone"> @Html.ActionLink("Sil", "DeleteSaloon", new { id = item.ID }, new { @class = "btn btn-danger" })  </td>
                        <td class="center hidden-phone">@Html.ActionLink("Güncelle", "UpdateSaloon", new { id = item.ID }, new { @class = "btn btn-warning" })</td>

                    </tr>
                }

            </tbody>
        </table>

    </div>
</div>

Project.MVCAdmin/Views/Saloon/UpdateSaloon.cshtml
@model AddUpdateSaloonPageVM
@{
    ViewBag.Title = "UpdateSaloon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="page-header">
    <h2>Saloon Güncelle</h2>

    <div class="right-wrapper text-end">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="bx bx-home-alt"></i>
                </a>
            </li>

            <li><span>Salonlar</span></li>

            <li><span>Salon Ekle</span></li>

        </ol>

    </div>
</header>
<!-- start: page -->
<div class="row">
    <div class="col">
        <section class="card">
            <header class="card-header">
                <div class="card-actions">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
                </div>

                <h2 class="card-title">Salon Ekle</h2>
            </header>
            <div class="card-body">
                @using (Html.BeginForm("UpdateSaloon", "Saloon", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.HiddenFor(x => x.Saloon.ID)
                    <form class="form-horizontal form-bordered" method="post" action="/Saloon/AddSaloon">


                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Salon Number</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x => x.Saloon.SaloonNumber, new { @class = "form-control" })
                            </div>
                        </div>



                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Salon Kapasitesi</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x => x.Saloon.Capacity, new { @class = "form-control" })

                            </div>
                        </div>
                        <div class="form-group row pb-4">
                            <div class="col-lg-3"></div>
                            <div class="col-lg-6">
                                <button type="submit" class="mb-1 mt-1 me-1 btn btn-gradient">Ekle</button>
                            </div>
                        </div>

                    </form>
                }
            </div>
        </section>
    </div>
</div>