Project.MVCAdmin/Controllers/AdminUserController.cs
using Project.BLL.Repositories.ConcRep;
using Project.ENTITIES.Models;
using Project.MVCAdmin.Models.CustomTools;
using Project.MVCAdmin.Models.PageVMs;
using Project.VM.AdminPureVMs;
using Project.VM.PureVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCAdmin.Controllers
{
    public class AdminUserController : Controller
    {
        AdminUserRepository _adminUserRep;
        public AdminUserController()
        {
            _adminUserRep = new AdminUserRepository();
        }


        public ActionResult Index()
        {
            List<AdminUserVM> adminUsers = _adminUserRep.Where(x => x.AdminRole != ENTITIES.Enums.AdminRole.Admin && x.Status != ENTITIES.Enums.DataStatus.Deleted).Select(x => new AdminUserVM
            {
                ID = x.ID,
                UserName = x.UserName,
                Password = x.Password,
                AdminRole = x.AdminRole,
                NameSurname = x.NameSurname,


            }).ToList();


            ListAdminUserPageVM adminUserListPageVM = new ListAdminUserPageVM()
            {
                AdminUsers = adminUsers,
            };

            return View(adminUserListPageVM);
        }


        public ActionResult AddAdminUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAdminUser(AdminUserVM adminUser)
        {
            AdminUser ap = new AdminUser
            {
               ID= adminUser.ID,
               UserName= adminUser.UserName,
               Password= adminUser.Password,
               AdminRole= adminUser.AdminRole,
               NameSurname=adminUser.NameSurname,

            };
            _adminUserRep.Add(ap);
            return View();
        }

        public ActionResult UpdateAdminUser(int? id)
        {
            AddUpdateAdminUserPageVM adminUserVM = new AddUpdateAdminUserPageVM()
            {
                 AdminUser = _adminUserRep.Where(x => x.ID == id).Select(x => new AdminUserVM
                {
                    ID = x.ID,
                    UserName = x.UserName,
                    NameSurname = x.NameSurname,
                    Password = x.Password,
                    AdminRole = x.AdminRole
                }).FirstOrDefault()
            };

            return View(adminUserVM);
        }


        [HttpPost]
        public ActionResult UpdateAdminUser(AdminUserVM adminUser)
        {
            AdminUser updated = _adminUserRep.Find(adminUser.ID);
            updated.UserName= adminUser.UserName;
            updated.NameSurname= adminUser.NameSurname;
            updated.Password= adminUser.Password;
            updated.AdminRole = adminUser.AdminRole;

            _adminUserRep.Update(updated);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAppUser(int id)
        {
            var adminUserToDelete = _adminUserRep.Find(id);

            _adminUserRep.Delete(adminUserToDelete);
            //_appUserRep.Delete(id);
            return RedirectToAction("Index");

        }

    }
}

Project.MVCAdmin/Views/User/AddAppUser.cshtml
@model AddUpdateAdminUserPageVM
@{
    ViewBag.Title = "AddAppUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<header class="page-header">
    <h2>Kullanıcı Ekle</h2>

    <div class="right-wrapper text-end">
    </div>
</header>

<div class="row">
    <div class="col">
        <section class="card">
            <header class="card-header">
                <div class="card-actions">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
                </div>

                <h2 class="card-title">Kullanıcı Ekle</h2>
            </header>
            <div class="card-body">
                @using (Html.BeginForm("AddAppUser", "User", FormMethod.Post, new { role = "form" }))
                {

                    <form class="form-horizontal form-bordered" method="post" action="/Saloon/AddSaloon">
                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">UserName</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x => x.AdminUser.UserName, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Password</label>
                            <div class="col-lg-6">
                                @Html.PasswordFor(x => x.AdminUser.Password, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Role</label>
                            <div class="col-lg-6">
                                @Html.EnumDropDownListFor(x => x.AdminUser.Roles, new { @class = "form-control-genislik" })

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2">İşlem:</label>
                            <div class="col-sm-10">
                                <button class="btn btn-primary">Ekle</button>
                            </div>
                        </div>
                    </form>
                }
            </div>
        </section>
    </div>
</div>

Project.MVCAdmin/Views/User/ListAppUser.cshtml
@model ListAdminUserPageVM
@{
    ViewBag.Title = "ListAppUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="panel-heading">
    @Html.ActionLink("User Ekle", "AddAppUser", null, new { @class = "btn btn-dark" })
</header>

<div class="panel-body">
    <div class="adv-table">
        <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
            <thead>
                <tr>
                    <th>User ID</th>
                    <th class="hidden-phone">UserName</th>
                    <th class="hidden-phone">User Role</th>


                    <th class="hidden-phone">Sil</th>
                    <th class="hidden-phone">Güncelle</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model.AdminUsers)
                {
                    <tr class="gradeX">




                        <td>@item.ID</td>
                        <td>@item.UserName</td>
                        
                        <td>@item.Roles</td>

                        <td class="center hidden-phone"> @Html.ActionLink("Sil", "DeleteAppUser", new { id = item.ID }, new { @class = "btn btn-danger" })  </td>
                        <td class="center hidden-phone">@Html.ActionLink("Güncelle", "UpdateAppUser", new { id = item.ID }, new { @class = "btn btn-warning" })</td>

                    </tr>
                 }

            </tbody>
        </table>

    </div>
</div>

Project.MVCAdmin/Views/User/UpdateAppUser.cshtml
@model AddUpdateAdminUserPageVM
@{
    ViewBag.Title = "UpdateAppUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("UpdateAppUser", "AdminUser", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.HiddenFor(x => x.AdminUser.ID)

    <div class="row">
        <div class="col-sm-12">

            <section class="panel">
                <header class="panel-heading">
                   Kullanıcı Güncelleme Sayfası
                </header>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="col-sm-2"> UserName</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.AdminUser.UserName, new { @class = "form-control-genislik" })
                        </div>
                    </div>

                    <br /> <br />
                    <div class="form-group">
                        <label class="col-sm-2">Password</label>
                        <div class="col-sm-10">
                            @Html.PasswordFor(x => x.AdminUser.Password, new { @class = "form-control", placeholder = "Şifre Belirleyiniz" })
                        </div>
                    </div>
                    <br /> <br />
                    <div class="form-group">
                        <label class="col-sm-2">Roles</label>
                        <div class="col-sm-10">
                            <select name="combobox" multiple>
                                <option value="value1">Admin</option>
                                <option value="value2">BoxOfficeAttendant</option>
                                <option value="value3"> BoxOfficeSupervisor</option>
                                <option value="value2">DepartmanManager</option>
                                <option value="value3"> Member</option>
                                <option value="value3">VIP</option>
                            </select>

                        </div>
                    </div>
                    <div class="form-group">

                        <div class="form-group">
                            <label class="col-sm-2">İşlem:</label>
                            <div class="col-sm-10">
                                <button class="btn btn-primary">Güncelle</button>

                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
 }