Project.MVCUI/Controllers/RegisterUserController.cs
using Project.BLL.Repositories.ConcRep;
using Project.COMMON.Tools;
using Project.ENTITIES.Enums;
using Project.ENTITIES.Models;
using Project.VM.PureVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCUI.Controllers
{
    public class RegisterUserController : Controller
    {
        AppUserRepository _appUserRep;
        AppUserProfileRepository _appProfileRep;
        public RegisterUserController()
        {
            _appUserRep = new AppUserRepository();
            _appProfileRep = new AppUserProfileRepository();
        }


        public ActionResult Index()
        {

            return View();
        }


        public ActionResult RegisterNow()
        {
            return View();
        }


        [HttpPost]
        public ActionResult RegisterNow(AppUserVM appUser, AppUserProfile profile)
        {
            if (_appUserRep.Any(x => x.UserName == appUser.UserName))
            {
                ViewBag.Kayitli = "Kayıtlı Kullanıcı Adı";
                return View();
            }
            else if (_appUserRep.Any(x => x.Email == appUser.Email))
            {
                ViewBag.Kayitli = "Kayıtlı Email Adı";
                return View();
            }

            appUser.Password = CryptPassword.Crypt(appUser.Password);

            AppUser addUser = new AppUser
            {
                UserName = appUser.UserName,
                Password = appUser.Password,
                Email = appUser.Email,
            };

            _appUserRep.Add(addUser);

            string kayitMail = "Hoş Geldiniz Hesabınız oluşturuldu, Hesabı aktif etmek için Linke Tıklayınız \n  http://localhost:62653/RegisterUser/ActivationUser/" + addUser.ActivationCode;

            MailService.Send(appUser.Email, body: kayitMail, subject: "Hesap Aktivasyonu ! ! !");
            if (!string.IsNullOrEmpty(profile.FirstName.Trim()) || !string.IsNullOrEmpty(profile.LastName.Trim()))
            {
                AppUserProfile addProfile = new AppUserProfile
                {
                    ID = addUser.ID,
                    FirstName = profile.FirstName,
                    LastName = profile.LastName,
                    Job = profile.Job,
                    Gender = profile.Gender,
                    BirthDate = profile.BirthDate,
                };
                _appProfileRep.Add(addProfile);

            }


            return View("RegisterOk");
        }


        public ActionResult LoginUser()
        {
            return View();
        }


        [HttpPost]
        public ActionResult LoginUser(AppUserVM appUser)
        {
            AppUser login = _appUserRep.FirstOrDefault(x => x.UserName.Equals(appUser.UserName) || x.Email.Equals(appUser.Email));

            if (login != null)
            {
                return RedirectToAction("Index","Home");
            }
            return View();
        }

        public ActionResult ActivationUser(Guid id)
        {
            AppUser isActive = _appUserRep.FirstOrDefault(x => x.ActivationCode == id);
            if (isActive != null)
            {
                isActive.Active = true;
                _appUserRep.Update(isActive);
                TempData["HesapAktifMi"] = "Hesap Aktif Hale Getirildi";
                return RedirectToAction("Index","Home");
            }
            TempData["HesapAktifMi"] = "Hesabınız bulunamadı";
            return RedirectToAction("LoginUser");
        }

        public ActionResult RegisterOk()
        {
            return View();
        }

    }
}

Project.MVCUI/Controllers/VipController.cs
using Microsoft.Ajax.Utilities;
using Project.BLL.Repositories.ConcRep;
using Project.COMMON.Tools;
using Project.ENTITIES.Models;
using Project.VM.PureVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCUI.Controllers
{
    public class VipController : Controller
    {
        AppUserRepository _appUser;
        public VipController()
        {
            _appUser = new AppUserRepository();
        }

        [HttpGet]
        public ActionResult ActivationCode()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ActivationCode(AppUserVM appUser)
        {
            // Aktivasyon kodu ile müşteriyi yakala
            AppUser user = _appUser.FirstOrDefault(x => x.ActivationCode == new Guid(appUser.ActivationCode));

            if (user == null)
            {
                return RedirectToAction("Error", "Activation");
            }

            string newVipCode = GenerateRandomCode(10);

            user.Role = ENTITIES.Enums.UserRole.VIP;
            user.VipCode = newVipCode;
            user.CreatedAt = DateTime.Now;

            _appUser.Update(user);

            string active = "Tebrikler ödemeniz alındı size özel giriş kodu şöyledir:" + Environment.NewLine + newVipCode;

            MailService.Send(user.Email, body: active, subject: "Vip Code");

            return RedirectToAction("LoginUser", "RegisterUser");
        }

        private string GenerateRandomCode(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            var rnd = new Random();
            return new string(Enumerable.Repeat(chars, length).
                Select(s => s[rnd.Next(s.Length)]).ToArray());

        }


    }
}

Project.MVCUI/Views/RegisterUser/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Kod doğru</h2>

Project.MVCUI/Views/RegisterUser/LoginUser.cshtml
@model RegisterNowUserPageVM
@{
    ViewBag.Title = "LoginUser";
}



@using (Html.BeginForm("LoginUser", "RegisterUser", FormMethod.Post))
{
    <div class="center-sign">
        <a href="/" class="logo float-start">
            <img src="~/Content/img/logo.png" height="70" alt="Porto Admin" />
        </a>

        <div class="panel card-sign">
            <div class="card-title-sign mt-3 text-end">
                <h2 class="title text-uppercase font-weight-bold m-0"><i class="bx bx-user-circle me-1 text-6 position-relative top-5"></i> Sign In</h2>
            </div>

            <div class="card-body">
                <form action="index.html" method="post">
                    <div class="form-group mb-3">
                        <label>Username</label>
                        <div class="input-group">
                            @Html.TextBoxFor(x => x.AppUser.UserName, new { @class = "form-control" })
                            <span class="input-group-text">
                                <i class="bx bx-user text-4"></i>
                            </span>
                        </div>
                    </div>

                    @*<div class="form-group mb-3">
                            <div class="clearfix">
                                <label class="float-start">Email</label>
                            </div>

                            <div class="input-group">
                                <input name="email" type="email" class="form-control form-control-lg" />
                                <span class="input-group-text">
                                    <i class="bx bx-mail-send"></i>
                                </span>
                            </div>
                        </div>*@

                    <div class="form-group mb-3">
                        <div class="clearfix">
                            <label class="float-start">Password</label>
                            <a href="pages-recover-password.html" class="float-end">Lost Password?</a>
                        </div>

                        <div class="input-group">
                            @Html.TextBoxFor(x => x.AppUser.Password, new { @class = "form-control" })
                            <span class="input-group-text">
                                <i class="bx bx-lock text-4"></i>
                            </span>
                        </div>
                    </div>




                    <div class="row">
                        <div class="col-sm-8">
                            <div class="checkbox-custom checkbox-default">
                                <input id="RememberMe" name="rememberme" type="checkbox" />
                                <label for="RememberMe">Remember Me</label>
                            </div>
                        </div>
                        <div class="col-sm-4 text-end">
                            <button type="submit" class="btn btn-primary mt-2">Sign In</button>
                        </div>
                    </div>

                    <span class="mt-3 mb-3 line-thru text-center text-uppercase">
                        <span>or</span>
                    </span>

                    @*<div class="mb-1 text-center">
                            <a class="btn btn-facebook mb-3 ms-1 me-1" href="#">Connect with <i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-twitter mb-3 ms-1 me-1" href="#">Connect with <i class="fab fa-twitter"></i></a>
                        </div>*@

                    <p class="text-center">Don't have an account yet? <a href="RegisterNow/RegisterUser">Sign Up!</a></p>
                    <p class="text-center">VIP KAYIT <a href="@Url.Action("ActivationCode", "Vip")">Kayıt OL !!</a></p>

                </form>
            </div>
        </div>

        <p class="text-center text-muted mt-3 mb-3">&copy; Copyright 2021. All Rights Reserved.</p>
    </div>
}

Project.MVCUI/Views/RegisterUser/RegisterNow.cshtml
@model RegisterNowUserPageVM
@{
    ViewBag.Title = "RegisterNow";
}



<h2>@ViewBag.Kayitli</h2>


@using (Html.BeginForm("RegisterNow", "RegisterUser", FormMethod.Post, new { @class = "form-signin" }))
{
    <br />

    <center><h2>Üye olunuz</h2></center>

    <div class="login-wrap">
        @Html.TextBoxFor(x => x.AppUser.UserName, new { @class = "form-control", placeholder = "Kullanıcı ismi belirleyin" })
        @Html.PasswordFor(x => x.AppUser.Password, new { @class = "form-control", placeholder = "Sifre belirleyin" })
        @Html.TextBoxFor(x => x.AppUser.Email, new { @class = "form-control", placeholder = "Email giriniz" })


        <br />

        Profil bilgileri (iste baglı)

        <br />

        @Html.TextBoxFor(x => x.Profile.FirstName, new { @class = "form-control", placeholder = "İsminizi giriniz" })
        @Html.TextBoxFor(x => x.Profile.LastName, new { @class = "form-control", placeholder = "Soyisim giriniz" })
        <label for="gender">Cinsiyet:</label><br />
        <label>
            @Html.RadioButtonFor(x => x.Profile.Gender, "Male")
            Male
        </label><br />
        <label>
            @Html.RadioButtonFor(x => x.Profile.Gender, "Female")
            Female
        </label>


        <div class="form-group row pb-4">
            <label class="col-lg-3 control-label text-lg-end pt-2"
                   for="inputDefault"></label>
            <div class="col-lg-6">
                @Html.TextBoxFor(x => x.Profile.BirthDate, new { type = "datetime-local" })

            </div>
        </div>


        <button class="btn btn-primary">Üye ol</button>

        @*<div>
            @Html.ActionLink("Giriş yap", "Index", "RegisterUser")
        </div>*@


    </div>
}




  

Project.MVCUI/Views/RegisterUser/RegisterOk.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Kayıt Başarılı</title>
    <style>
        body {
            background-color: #f0f0f0;
            font-family: Arial, sans-serif;
        }

        .jumbotron {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            margin: 50px auto;
            padding: 20px;
            text-align: center;
            width: 400px;
        }

        h1 {
            font-size: 24px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="jumbotron">
        <h1>Tebrikler, Kayıt Oldunuz!</h1>
        <p>Lütfen Email adresinize gönderdiğimiz aktivasyon linkini tıklayarak hesabınızı aktifleştirin.</p>
    </div>

    <script>
        
        setTimeout(function () {
            window.location = "/RegisterUser/Index";
        }, 5000);
    </script>
</body>
</html>
<h2>@TempData["HesapAtkifMi"]</h2>