Project.MVCAdmin/Controllers/FilmController.cs
using Project.BLL.Repositories.ConcRep;
using Project.ENTITIES.Models;
using Project.MVCAdmin.Models.CustomTools;
using Project.MVCAdmin.Models.PageVMs;
using Project.VM.PureVMs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCAdmin.Controllers
{
    public class FilmController : Controller
    {
        FilmRepository _filmRep;
        SeansRepository _seansRep;
        public FilmController()
        {
            _filmRep = new FilmRepository();
            _seansRep = new SeansRepository();
        }

        private List<FilmVM> GetFilms()
        {
            return _filmRep.Where(x => x.Status != ENTITIES.Enums.DataStatus.Deleted).Select(x => new FilmVM
            {
                ID = x.ID,
                MovieName = x.MovieName,
                Duration = x.Duration,
                ImagePath = x.ImagePath,
                Info = x.Info,
                Type = x.Type,

            }).ToList();
        }

        public ActionResult Index()
        {
            List<FilmVM> films = GetFilms();
            ListFilmPageVM lpvm = new ListFilmPageVM
            {
                Films = films,
            };
            _filmRep.GetAll();
            return View(lpvm);

        }

        public ActionResult AddFilm()
        {
            return View();
        }

        [HttpPost]

        // film bitince başka seansla cakısmasın 

        public ActionResult AddFilm(FilmVM film, HttpPostedFileBase image, string fileName)
        {
          var _fileNameWithGuid=  ImageUploader.UploadImage("/Pictures/", image, fileName);

            Film f = new Film
            {
                MovieName = film.MovieName,
                ID = film.ID,
                Duration = film.Duration,
                ImagePath = _fileNameWithGuid,
                Info = film.Info,
                Type = film.Type,

            };
            _filmRep.Add(f);
            return RedirectToAction("Index");
        }


        public ActionResult UpdateFilm(int id)
        {
            AddUpdateFilmPageVM flpvm = new AddUpdateFilmPageVM
            {
                Film = _filmRep.Where(x => x.ID == id).Select(x => new FilmVM
                {
                    ID = x.ID,
                    MovieName = x.MovieName,
                    Duration = x.Duration,
                    ImagePath = x.ImagePath,
                    Type = x.Type,
                    Info = x.Info,

                }).FirstOrDefault()
            };
            return View(flpvm);
        }

        [HttpPost]
        public ActionResult UpdateFilm(FilmVM film, HttpPostedFileBase image)
        {
            var _fileNameWithGuid = ImageUploader.UploadImage("/Pictures/", image, image.FileName);
            Film updated = _filmRep.Find(film.ID);
            updated.MovieName = film.MovieName;
            updated.Duration = film.Duration;
            updated.ImagePath = _fileNameWithGuid;
            updated.Type = film.Type;
            updated.Info = film.Info;

            List<Seans> updateSeans = _seansRep.Where(x => x.FilmId == updated.ID).ToList();
            foreach (Seans seans in updateSeans)
            {
                seans.Film.Duration = updated.Duration;
                DateTime endTime = seans.StartTime.AddMinutes(updated.Duration + 10);
                seans.EndTime = endTime;
                _seansRep.Update(seans);

            }
            _filmRep.Update(updated);

            return RedirectToAction("Index");

        }

        public ActionResult DeleteFilm(int id)
        {
            Film film = _filmRep.Find(id);

            List<Seans> seanslar = _seansRep.Where(x => x.FilmId == film.ID);

            _seansRep.DeleteRange(seanslar);

            _filmRep.Delete(film);

            return RedirectToAction("Index");

        }
    }
}

Project.MVCAdmin/Views/Film/AddFilm.cshtml
@model AddUpdateFilmPageVM
@{
    ViewBag.Title = "AddFilm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="page-header">
    <h2>Film Ekle</h2>

    <div class="right-wrapper text-end">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="bx bx-home-alt"></i>
                </a>
            </li>

            <li><span>Filmler</span></li>

            <li><span>Film Ekle</span></li>

        </ol>

    </div>
</header>

<!-- start: page -->
<div class="row">
    <div class="col">
        <section class="card">
            <header class="card-header">
                <div class="card-actions">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
                </div>

                <h2 class="card-title">Film Ekle</h2>
            </header>
            <div class="card-body">
                @using (Html.BeginForm("AddFilm","Film",FormMethod.Post, new { enctype = "multipart/form-data" }))
                {

                    <form class="form-horizontal form-bordered" method="post" action="/Film/AddFilm">


                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Film Adı</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x=> x.Film.MovieName, new {@class="form-control"})
                            </div>
                        </div>



                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Film Süresi</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x => x.Film.Duration, new { @class = "form-control" })

                            </div>
                        </div>

                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Film Türü</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x => x.Film.Type, new { @class = "form-control" })

                            </div>
                        </div>

                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Film Bilgisi</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x => x.Film.Info, new { @class = "form-control" })

                            </div>
                        </div>

                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Resim</label>

                            <input type="file" name="image" class="form-control genislik" />
                            <br />

                            @Html.TextBox("fileName", null, new { @class = "form-control-genislik", placeholder = "Resim ismi giriniz" })
                        </div>


                        <div class="form-group row pb-4">
                            <div class="col-lg-3"></div>
                            <div class="col-lg-6">
                                <button type="submit" class="mb-1 mt-1 me-1 btn btn-primary">Ekle</button>
                            </div>
                        </div>

                    </form>
                }
            </div>
        </section>
    </div>
</div>

Project.MVCAdmin/Views/Film/Index.cshtml
@model ListFilmPageVM
@{
    ViewBag.Title = "ListFilms";
}

<header class="page-header">
    <h2>Film Listesi</h2>

    <div class="right-wrapper text-end">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="bx bx-home-alt"></i>
                </a>
            </li>

            <li><span>Film Yönetimi</span></li>

            <li><span>Film Listesi</span></li>

        </ol>

    </div>
</header>

<!-- start: page -->
<section class="card">
    <header class="card-header">

        <h2 class="card-title">Film Listesi</h2>
    </header>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-3">
                    <a id="addToTable" href="/Film/AddFilm" class="btn btn-primary">Yeni Ekle <i class="fas fa-plus"></i></a>
                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped mb-0" id="datatable-editable">
            <thead>
                <tr>
                    
                    <th>Film Adı</th>
                    <th>Film Süresi</th>
                    <th>Tipi</th>
                    <th>Film Bilgisi</th>
                    <th>Fotoğraf</th>
                </tr>
            </thead>
            <tbody>
                @foreach (FilmVM item in Model.Films)
                {
                    <tr data-item-id="1">
                        <td>
                            @item.MovieName
                        </td>
                        <td>
                            @item.Duration
                        </td>
                        <td>
                            @item.Type
                        </td>
                        <td>
                            @item.Info
                        </td>
                        <td>
                            <img width="30" height="30" title="@item.MovieName" src="/Pictures/@item.ImagePath" />
                        </td>

                       
                        <td class="actions">
                            <a href="/Film/UpdateFilm/@item.ID" class="on-default edit-row"><i class="fas fa-pencil-alt"></i></a>
                            <a href="/Film/DeleteFilm/@item.ID" class="on-default remove-row"
                               onclick="return confirm('Bu filmi sildiğinizde bağlı olan tüm seansları da silinecketir! Bu filmi silmek istediğinize emini misinniz ? ')">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>
<!-- end: page -->

Project.MVCAdmin/Views/Film/ListFilms.cshtml
@model ListFilmPageVM
@{
    ViewBag.Title = "ListFilms";
}

<header class="page-header">
    <h2>Film Listesi</h2>

    <div class="right-wrapper text-end">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="bx bx-home-alt"></i>
                </a>
            </li>

            <li><span>Film Yönetimi</span></li>

            <li><span>Film Listesi</span></li>

        </ol>

    </div>
</header>

<!-- start: page -->
<section class="card">
    <header class="card-header">

        <h2 class="card-title">Salon Listesi</h2>
    </header>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-3">
                    <a id="addToTable" href="/Film/AddFilm" class="btn btn-primary">Yeni Ekle <i class="fas fa-plus"></i></a>
                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped mb-0" id="datatable-editable">
            <thead>
                <tr>
                    <
                    <th>Film Adı</th>
                    <th>Film Süresi</th>
                    <th>Tipi</th>
                    <th>Film Bilgisi</th>
                    <th>Fotoğraf</th>
                </tr>
            </thead>
            <tbody>
                @foreach (FilmVM item in Model.Films)
                {
                    <tr data-item-id="1">
                        <td>
                            @item.MovieName
                        </td>
                        <td>
                            @item.Duration
                        </td>
                        <td>
                            @item.Type
                        </td>
                        <td>
                            @item.Info
                        </td>
                        <td>
                            <img width="30" height="30" title="@item.MovieName" src="@item.ImagePath" />
                        </td>

                       
                        <td class="actions">
                            <a href="/Film/UpdateFilm/@item.ID" class="on-default edit-row"><i class="fas fa-pencil-alt"></i></a>
                            <a href="/Film/DeleteFilm/@item.ID" class="on-default remove-row"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>
<!-- end: page -->

Project.MVCAdmin/Views/Film/UpdateFilm.cshtml
@model AddUpdateFilmPageVM
@{
    ViewBag.Title = "UpdateFilm";
}

<header class="page-header">
    <h2>Film Güncelle</h2>

    <div class="right-wrapper text-end">
        <ol class="breadcrumbs">
            <li>
                <a href="index.html">
                    <i class="bx bx-home-alt"></i>
                </a>
            </li>

            <li><span>Filmler</span></li>

            <li><span>Film Ekle</span></li>

        </ol>

    </div>
</header>

<!-- start: page -->
<div class="row">
    <div class="col">
        <section class="card">
            <header class="card-header">
                <div class="card-actions">
                    <a href="#" class="card-action card-action-toggle" data-card-toggle></a>
                    <a href="#" class="card-action card-action-dismiss" data-card-dismiss></a>
                </div>

                <h2 class="card-title">Film Ekle</h2>
            </header>
            <div class="card-body">
                @using (Html.BeginForm("UpdateFilm", "Film", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.HiddenFor(x=> x.Film.ID)
                    <form class="form-horizontal form-bordered" method="post" action="/Film/AddFilm">


                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Film Adı</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x => x.Film.MovieName, new { @class = "form-control" })
                            </div>
                        </div>



                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Film Süresi</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x => x.Film.Duration, new { @class = "form-control" })

                            </div>
                        </div>

                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Film Türü</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x => x.Film.Type, new { @class = "form-control" })

                            </div>
                        </div>

                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Film Bilgisi</label>
                            <div class="col-lg-6">
                                @Html.TextBoxFor(x => x.Film.Info, new { @class = "form-control" })

                            </div>
                        </div>

                        <div class="form-group row pb-4">
                            <label class="col-lg-3 control-label text-lg-end pt-2"
                                   for="inputDefault">Resim</label>

                            <input type="file" name="image" class="form-control genislik" />
                            <br />

                            @Html.TextBox("fileName", null, new { @class = "form-control-genislik", placeholder = "Resim ismi giriniz" })
                        </div>


                        <div class="form-group row pb-4">
                            <div class="col-lg-3"></div>
                            <div class="col-lg-6">
                                <button type="submit" class="mb-1 mt-1 me-1 btn btn-primary">Ekle</button>
                            </div>
                        </div>

                    </form>
                }
            </div>
        </section>
    </div>
</div>